[package]
name = "bums"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.12"
clap = { version = "4.4.6", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.20"
rand = "0.8.5"
predicates = "3.0.4"
z3 = {version = "0.12.1", features = ["static-link-z3"]}
