[package]
name = "bums_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
full = "0.1.0"
quote = "1.0.35"
syn = "2.0.49"
bums = { path = "../memsafe-checker" }
