[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
runner = "qemu-aarch64"


[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]
